name: flutter_midi_command_web
description: FlutterMidiCommand for the web.
version: 0.0.1
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterMidiCommandWeb
        fileName: flutter_midi_command_web.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface:
    path: "../flutter_midi_command_platform_interface"
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
